
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: microservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
